{
 "title": "HU Perf",
 "time": { "from": "2023-08-15T21:00:00.000Z", "to": "2023-08-15T23:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "SN", "query": { "query": "label_values(SN)" } },
   {
    "name": "Resource",
    "query": {
     "query": "label_values({SN=~\"$SN\"},Resource)"
    }
   },
   {
    "name": "Element",
    "query": {
     "query": "label_values({SN=~\"$SN\", Resource=~\"$Resource\"},Element)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Avg usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hu_avg_cpu_usage_pct_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "KV CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hu_kv_cpu_usage_pct_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Max BW, Mbps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_max_bandwidth_mbps_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Block BW, Mbps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_block_bandwidth_mbps_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Read BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_read_bandwidth_mbps_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Write BW",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_write_bandwidth_mbps_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Max IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_max_iops_iops_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_read_iops_iops_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_write_iops_iops_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Read disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_read_disk_iopsiops_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  },
  {
   "title": "Write disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hu_write_disk_iopsiops_variable{SN=~\"$SN\", Resource=~\"$Resource\", Element=~\"$Element\"}",
     "legendFormat": "{{Resource}}_{{Element}}_{{SN}}"
    }
   ]
  }
 ]
}